theme: jekyll-theme-cayman
title: Panduan Umat Sathora Daftar Misa Tatap Muka 
description: Tata cara pemutakhiran data vaksinasi COVID-19 di BIDUK dan pendaftaran misa tatap muka.
owner_name: TGKP/TABP Bojong Indah
version: 2108251602
show-downloads: false
github:
  is_project_page: false
