theme: jekyll-theme-cayman
title: Panduan Umat Hadiri Misa di Gereja Sathora
description: Tata cara pemutakhiran data vaksin Covid-19 di BIDUK, pendaftaran misa, dan proses skrining [Revisi 8/04/2022].
owner_name: TGKPBI+TABBI
version: 220408
show-downloads: false
github:
  is_project_page: false
