theme: jekyll-theme-leap-day
title: Tata Cara Umat Sathora Daftar Misa Tatap Muka 
description: Panduan pemutakhiran data vaksinasi COVID-19 di BIDUK dan pendaftaran misa tatap muka.
version: 25/08/2021 09:47
show-downloads: false
github:
  is_project_page: false
  owner_name: TGKP/TABP Bojong Indah
