theme: jekyll-theme-cayman
title: BIDUK: Umat Sathora Lapor Sertifikat Vaksinasi
description: Info tata cara pendaftaran misa tatap muka, penyimpanan data vaksinasi COVID-19 di BIDUK
show-downloads: false
github:
  is_project_page: false
