theme: jekyll-theme-cayman
title: Panduan Umat Sathora Mendaftar Misa di Gereja
description: Tata cara pemutakhiran data vaksin Covid-19 di BIDUK dan pendaftaran misa tatap muka [Revisi 14/09/2021].
owner_name: TGKP/TABP Bojong Indah
version: 2109141244
show-downloads: false
github:
  is_project_page: false
