theme: jekyll-theme-cayman
title: BIDUK: Umat Sathora Lapor Sertifikat Vaksinasi
description: Info tata cara pelaporan umat yang telah menerima vaksinasi COVID-19
show-downloads: false
github:
  is_project_page: false
