theme: jekyll-theme-cayman
title: Umat Sathora Lapor Vaksinasi-BIDUK
description: Info pelaporan umat yang telah menerima vaksinasi untuk mendaftar misa tatap muka
show-downloads: false
github:
  is_project_page: false
