theme: jekyll-theme-cayman
title: Panduan Umat Hadiri Misa di Gereja Sathora
description: Tata cara pemutakhiran data vaksin Covid-19 di BIDUK, pendaftaran misa, dan proses skrining [Revisi 30/09/2021].
owner_name: TGKPBI+TABBI
version: 210930
show-downloads: false
github:
  is_project_page: false
