theme: jekyll-theme-leap-day
title: Tata Cara Umat Sathora Daftar Misa Tatap Muka 
description: Info tata cara penyimpanan data vaksinasi COVID-19 di BIDUK dan pendaftaran misa tatap muka.
show-downloads: false
github:
  is_project_page: false
