theme: jekyll-theme-cayman
title: Panduan Umat Sathora Hadiri Misa di Gereja
description: Tata cara pemutakhiran data vaksin Covid-19 di BIDUK, pendaftaran misa, dan proses skrining [Revisi 14/09/2021].
owner_name: TGK/TAB Paroki Bojong Indah
version: 2109141244
show-downloads: false
github:
  is_project_page: false
